"""empty message

Revision ID: 102472a595a
Revises: None
Create Date: 2015-08-06 20:21:42.511803

"""

# revision identifiers, used by Alembic.
revision = '102472a595a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.String(length=300), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=300), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('time', sa.String(length=300), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('winner', sa.String(length=300), nullable=True),
    sa.Column('fav_trump', sa.String(length=300), nullable=True),
    sa.Column('fav_bush', sa.String(length=300), nullable=True),
    sa.Column('fav_walker', sa.String(length=300), nullable=True),
    sa.Column('fav_carson', sa.String(length=300), nullable=True),
    sa.Column('fav_huckabee', sa.String(length=300), nullable=True),
    sa.Column('fav_cruz', sa.String(length=300), nullable=True),
    sa.Column('fav_rubio', sa.String(length=300), nullable=True),
    sa.Column('fav_paul', sa.String(length=300), nullable=True),
    sa.Column('fav_christie', sa.String(length=300), nullable=True),
    sa.Column('fav_kasich', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('response')
    op.drop_table('assignment')
    ### end Alembic commands ###
