"""empty message

Revision ID: 13ed17777eb
Revises: 102472a595a
Create Date: 2015-09-16 18:57:47.167968

"""

# revision identifiers, used by Alembic.
revision = '13ed17777eb'
down_revision = '102472a595a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
