"""empty message

Revision ID: 4908036c7de
Revises: 13ed17777eb
Create Date: 2015-09-16 19:10:08.456272

"""

# revision identifiers, used by Alembic.
revision = '4908036c7de'
down_revision = '13ed17777eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response', sa.Column('fav_fiorina', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('response', 'fav_fiorina')
    ### end Alembic commands ###
