"""empty message

Revision ID: 4ba4e786aef
Revises: 4908036c7de
Create Date: 2015-09-16 19:19:51.602139

"""

# revision identifiers, used by Alembic.
revision = '4ba4e786aef'
down_revision = '4908036c7de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
